FROM ubuntu:20.04
MAINTAINER Haproxy-thongth

RUN apt update -y && \
    apt upgrade -y


RUN DEBIAN_FRONTEND=noninteractive TZ=Asia/Ho_Chi_Minh apt-get -y install tzdata

RUN apt install tcpdump \
    traceroute  \
    net-tools \
    vim  -y

RUN apt install haproxy -y

ADD entrypoint.sh /
ADD haproxy/ /etc/haproxy/
ADD haproxy_run.sh /etc/haproxy/

RUN chmod +x /etc/haproxy/haproxy_run.sh
RUN chmod +x /entrypoint.sh



RUN mkdir /run/haproxy

ENTRYPOINT ["/entrypoint.sh"]

