version: '2'

services:
 haproxy:
  image: thongth1998/haproxy-vault:latest
  container_name: haproxy
  restart: always
  volumes:
    - "haproxy_socket:/run/haproxy:rw"
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/haproxy/:/etc/haproxy:rw"
  network_mode: "host"
  cap_drop:
    - NET_ADMIN
  privileged: true
volumes:
        haproxy_socket:
                external: true
